UPDATE questions SET explanation = '後ろに従属節が続いているため、"Although" のような従属接続詞が必要です。"Despite" や "In spite (of)" は節ではなく名詞句を伴い、"Because of" では意味が逆になってしまいます。' WHERE id = 'q-struct-c01';
UPDATE questions SET explanation = '文頭に "Not until..." が来ると主語と助動詞の倒置が起こり、"did + 主語 + 動詞の原形" の語順になります。' WHERE id = 'q-struct-c02';
UPDATE questions SET explanation = '"request that" は仮定法現在を要求する動詞で、時制に関係なく原形の "be submitted" を使います。' WHERE id = 'q-struct-c03';
UPDATE questions SET explanation = '"neither" はちょうど2つのものについて使い、"none" は3つ以上の場合に使います。' WHERE id = 'q-struct-c04';
UPDATE questions SET explanation = '「建設(工事)」が「新館」に属することを示すには所有格の関係代名詞が必要で、"whose" は人にも物にも使えます。' WHERE id = 'q-struct-c05';
UPDATE questions SET explanation = '"It is essential that" の後には仮定法現在の原形 "review" が必要です。' WHERE id = 'q-struct-c06';
UPDATE questions SET explanation = '後ろに名詞句("increasing air travel")が続いているため、接続詞や副詞ではなく "Despite" のような前置詞が必要です。' WHERE id = 'q-struct-c07';
UPDATE questions SET explanation = '"strong" のような1音節の形容詞は "more" ではなく "-er" を付けて比較級を作ります。' WHERE id = 'q-struct-c08';
UPDATE questions SET explanation = '否定的な意味を持つ副詞 "Rarely" が文頭に来ると倒置が起こり、"has + 主語 + been" の語順になります。' WHERE id = 'q-struct-c09';
UPDATE questions SET explanation = '間接疑問文(埋め込み疑問文)では疑問詞の倒置は起こらず、通常の語順を使います。したがって "explained why the experiment had failed" となります。' WHERE id = 'q-struct-c10';
UPDATE questions SET explanation = '"in an effort to + 動詞" は "in order to"(〜するために)と同じ意味を表す定型表現です。' WHERE id = 'q-struct-c11';
UPDATE questions SET explanation = '"data" は "datum" の複数形であり、日常会話では単数扱いされることも多いですが、フォーマルな英語(試験で問われる英語)では複数動詞 "were" を取ります。' WHERE id = 'q-struct-c12';
UPDATE questions SET explanation = 'これは過去の事実に反する仮定を表す仮定法過去完了(第3条件文)で、"could have been prevented" に対応するif節には "had been" が必要です。' WHERE id = 'q-struct-c13';
UPDATE questions SET explanation = '文頭に "Only after..." が来ると主節で主語と助動詞の倒置が起こり、"did + 主語 + 動詞の原形" の語順になります。' WHERE id = 'q-struct-c14';
UPDATE questions SET explanation = '"all" は複数名詞 "manufacturers" を正しく修飾できます。"every" と "each" は単数名詞を必要とし、"all of" を使うなら名詞の前に "the" が必要です。' WHERE id = 'q-struct-c15';
UPDATE questions SET explanation = '"not only... but also..."(〜だけでなく…も)は決まった相関接続詞のペアです。' WHERE id = 'q-struct-c16';
UPDATE questions SET explanation = '"recommend" の後には不定詞ではなく動名詞("completing")が続きます。' WHERE id = 'q-struct-c17';
UPDATE questions SET explanation = '"once" は「〜するとすぐに」という意味で、報告書を終えてから次の作業に取りかかるという時間的な流れに合います。' WHERE id = 'q-struct-c18';
UPDATE questions SET explanation = '主語 "findings" は複数形なので、現在形の動詞は "are" でなければなりません。' WHERE id = 'q-struct-c19';
UPDATE questions SET explanation = '"whether" の後には受動態の助動詞構文 "should be funded" が必要です。' WHERE id = 'q-struct-c20';
UPDATE questions SET explanation = '"has yet to + 動詞の原形" は「まだ〜していない」という意味を表す定型表現です。' WHERE id = 'q-struct-c21';
UPDATE questions SET explanation = '"the more..., the more..."(〜すればするほど…)という相関比較構文では、両方の比較級の前に "the" が必要です。' WHERE id = 'q-struct-c22';
UPDATE questions SET explanation = '"along with the accompanying illustrations" は挿入句であり、動詞は単数主語 "manuscript" に一致させて "was" にする必要があります。' WHERE id = 'q-struct-c23';
UPDATE questions SET explanation = '"few" は複数扱いの数量詞なので、動詞も複数形の "were" にする必要があります。' WHERE id = 'q-struct-c24';
UPDATE questions SET explanation = '関係代名詞 "which" は複数形の "results" を指しているため、動詞は "was" ではなく "were" にする必要があります。' WHERE id = 'q-struct-e01';
UPDATE questions SET explanation = '動詞 "declined" を修飾するには形容詞 "steady" ではなく副詞 "steadily" を使う必要があります。' WHERE id = 'q-struct-e02';
UPDATE questions SET explanation = '"each of the applicants" は文法上単数扱いなので、動詞は "were required" ではなく "was required" にする必要があります。' WHERE id = 'q-struct-e03';
UPDATE questions SET explanation = '"the number of" は単数動詞("has risen")を取ります。複数動詞を取る "a number of" とは異なるので注意が必要です。' WHERE id = 'q-struct-e04';
UPDATE questions SET explanation = '助動詞 "should" の後には受動態の原形 "be classified" が必要で、"be classify" という形は誤りです。' WHERE id = 'q-struct-e05';
UPDATE questions SET explanation = 'リストの列挙は名詞句として並列("two cups of flour"、"a teaspoon of salt"、"two beaten eggs")にそろえる必要がありますが、"beating the eggs" だけ動名詞句になっており、パラレリズム(並列構造)が崩れています。' WHERE id = 'q-struct-e06';
UPDATE questions SET explanation = '数量詞 "several" の後には複数名詞が必要なので、"several side effect" ではなく "several side effects" が正しい形です。' WHERE id = 'q-struct-e07';
UPDATE questions SET explanation = '過去完了形では原形の "destroy" ではなく過去分詞を使った "had already destroyed" にする必要があります。' WHERE id = 'q-struct-e08';
UPDATE questions SET explanation = '関係代名詞 "which" は複数形の "findings" を指しているため、動詞は "was" ではなく "were" にする必要があります。' WHERE id = 'q-struct-e09';
UPDATE questions SET explanation = '動詞 "worked" を修飾するには形容詞 "quick" ではなく副詞 "quickly" を使う必要があります。' WHERE id = 'q-struct-e10';
UPDATE questions SET explanation = '正しい表現は "responsible to ensure" ではなく "responsible for ensuring" です。' WHERE id = 'q-struct-e11';
UPDATE questions SET explanation = '"preferable" はそれ自体に比較の意味(「より望ましい」)が含まれているため、"more" を付けるのは冗長です。単に "preferable" とすべきです。' WHERE id = 'q-struct-e12';
UPDATE questions SET explanation = '"by next year" は未来のある時点までに完了している動作を示すため、未来完了形 "will have completed" が必要です。' WHERE id = 'q-struct-e13';
UPDATE questions SET explanation = 'リストは "write"、"organize"、"present" という並列構造を保つべきですが、"to present" だけ "to" を繰り返しており、パラレリズムが崩れています。' WHERE id = 'q-struct-e14';
UPDATE questions SET explanation = '主語 "complaints" は複数形なので、there構文では "There has been" ではなく "There have been" が必要です。' WHERE id = 'q-struct-e15';
UPDATE questions SET explanation = '"rainfall" は不可算名詞なので、可算名詞に使う "fewer" ではなく "less" で修飾する必要があります。' WHERE id = 'q-struct-e16';
UPDATE questions SET explanation = '「book」を後ろから修飾する分詞構文(縮約関係詞節)なので、自動詞「lie(横たわる・置いてある)」の現在分詞「lying」が正解です。「lay」「lied」は定形動詞(文の述語になる形)であり、名詞を後置修飾する形にはなりません。' WHERE id = 'q-struct-c25';
UPDATE questions SET explanation = '「原稿(manuscript)」は「改訂する」のではなく「改訂される」側なので、受け身の過去分詞「Revised」が正解です。「Revising」や「Having revised」は能動の意味になってしまい、主語(原稿)と意味が合いません。' WHERE id = 'q-struct-c26';
UPDATE questions SET explanation = '「Having + 過去分詞」(完了分詞構文)は、主節の動作より前に完了した動作を表します。「Have」「To have」「Had」はこのような分詞構文の形を作れません。' WHERE id = 'q-struct-c27';
UPDATE questions SET explanation = '「since 2019」があることから、資金提供は過去に始まり現在まで続いていることがわかります。また図書館は「資金を提供される」側なので、現在完了の受動態「has been funded」が正解です。' WHERE id = 'q-struct-c28';
UPDATE questions SET explanation = '「提案書(proposal)」は「審査する」のではなく「審査される」側なので受け身が必要です。未来の受け身を正しく表す「will be reviewed」が正解です。' WHERE id = 'q-struct-c29';
UPDATE questions SET explanation = '現実に起こりうる未来の出来事を述べる「第1条件文」では、if節の中は現在形(rains)を使い、主節でwillを使います。if節の中では未来形(will rain)は使いません。' WHERE id = 'q-struct-c30';
UPDATE questions SET explanation = '主節が「would likely develop」となっていることから、現在の事実に反する仮定を表す「第2条件文」だとわかります。第2条件文のif節では動詞は過去形(put)を使います。' WHERE id = 'q-struct-c31';
UPDATE questions SET explanation = '他の文に組み込まれた間接疑問文では、疑問詞のあとは通常の平叙文の語順(主語+動詞)になります。「why she had chosen」が正しく、疑問文のような倒置(why did she)は間接疑問文では使いません。' WHERE id = 'q-struct-c32';
UPDATE questions SET explanation = '「money(お金)」は不可算名詞なので、可算名詞に使う「many」「a number of」「few」ではなく、不可算名詞を修飾する「much」を使います。' WHERE id = 'q-struct-c33';
UPDATE questions SET explanation = '「effort(努力)」は不可算名詞なので、不可算名詞に使う数量表現「a great deal of」が正解です。「a great number of」「many」「few」はいずれも可算名詞に使う表現です。' WHERE id = 'q-struct-c34';
UPDATE questions SET explanation = '「3 p.m.」のような時刻を表すときには前置詞「at」を使います(例: at 3 p.m.)。' WHERE id = 'q-struct-c35';
UPDATE questions SET explanation = '交差点の場所を表すときの決まった言い方は「at the corner of」です。この熟語をそのまま覚えておきましょう。' WHERE id = 'q-struct-c36';
UPDATE questions SET explanation = '「〜に基づいている」という意味の正しい連語(コロケーション)は「based on」です。この組み合わせで覚えておく必要があります。' WHERE id = 'q-struct-c37';
UPDATE questions SET explanation = '「〜から成る、〜で構成されている」という意味の正しい連語は「consist of」です。' WHERE id = 'q-struct-c38';
UPDATE questions SET explanation = '伝達動詞(ここではreported)が過去形の場合、that節の中の時制もそれに合わせて一つ過去にずらす「時制の一致」が起こります。そのため現在形「have」ではなく過去形「had」を使います。' WHERE id = 'q-struct-c39';
UPDATE questions SET explanation = '原因と結果を表す「so + 形容詞 + that」の構文が正解です。「such」を使う場合は「such compelling evidence」のように名詞句が必要になります。' WHERE id = 'q-struct-c40';
UPDATE questions SET explanation = '後ろに名詞(argument)が続く場合は「such + a/an + 形容詞 + 名詞 + that」の形を使います。「so」を使う場合は冠詞と名詞を省いて「so persuasive that」のようにします。' WHERE id = 'q-struct-c41';
UPDATE questions SET explanation = '「used to + 動詞の原形」は「以前はよく〜したものだ(今はもうしていない)」という過去の習慣を表します。' WHERE id = 'q-struct-c42';
UPDATE questions SET explanation = '「be used to + 動名詞/名詞」は「〜に慣れている」という意味で、ここでは「異なる時差の中で暮らすことに慣れている」という継続的な状態に合います。' WHERE id = 'q-struct-c43';
UPDATE questions SET explanation = '「get used to + 動名詞/名詞」は「〜に慣れていく」という変化の過程を表し、「数週間かかった」という文脈にぴったり合います。' WHERE id = 'q-struct-c44';
UPDATE questions SET explanation = '使役表現「have + 目的語 + 過去分詞」は「(人に頼んで)〜してもらう」という意味です。屋根の修理を業者に依頼する、という状況に合います。' WHERE id = 'q-struct-c45';
UPDATE questions SET explanation = '使役表現「get + 目的語 + 過去分詞」も「〜してもらう」という意味を表し、ここではこの受け身的な使役の形に合うのは「get」だけです。他の選択肢はこの形に当てはまりません。' WHERE id = 'q-struct-c46';
UPDATE questions SET explanation = '「patience(忍耐力)」のような抽象的な性質・概念を一般的な意味で述べるときには、冠詞をつけません。' WHERE id = 'q-struct-c47';
UPDATE questions SET explanation = '河川名には定冠詞「the」をつけるという決まりがあります(例: the Amazon River)。' WHERE id = 'q-struct-c48';
UPDATE questions SET explanation = '「It is crucial that」に続くthat節の中では、時制に関係なく動詞の原形(仮定法現在)を使います。ここでは受け身の原形「be refrigerated」が正解です。' WHERE id = 'q-struct-c49';
UPDATE questions SET explanation = 'コンマで挟まれ、主語を別の言葉で言い換える「同格」の部分には名詞句が入ります。「the leader(リーダー)」という名詞句が正解です。' WHERE id = 'q-struct-c50';
UPDATE questions SET explanation = '強調の助動詞「did」を動詞の原形「support」と組み合わせることで、「seemed inconclusive(結論が出ていないように見えた)」との対比を強めています。文脈は過去の話なので、現在形かつ単数用法の「does」は合いません。' WHERE id = 'q-struct-c51';
UPDATE questions SET explanation = '「It was X that ...」という強調構文(分裂文)で、「the unexpected drop in temperature(予想外の気温低下)」を強調しています。この構文の主語は必ず「It」になります。' WHERE id = 'q-struct-c52';
UPDATE questions SET explanation = '「That」は文の主語になれる名詞節を導くことができます。「What」だと意味が変わってしまい、「Which」は先行詞が必要で、「Because」が導く副詞節は文の主語にはなれません。' WHERE id = 'q-struct-c53';
UPDATE questions SET explanation = '目的を表す「in order to + 動詞の原形」が正解です。「so as」は単独では不完全な形であり、「for to」は正しい英語ではなく、「so that」の後には不定詞ではなく完全な節が必要です。' WHERE id = 'q-struct-c54';
UPDATE questions SET explanation = '後ろに主語と動詞を含む完全な節が続く場合、目的を表すには「so that + 節」を使います。「so as to」や「in order」の後には不定詞が続き、節は続きません。' WHERE id = 'q-struct-c55';
UPDATE questions SET explanation = '「Even if」は「たとえ〜だとしても」と、まだ不確かな仮定の状況を導きます。この文脈は仮定的な内容なので合いますが、「Even though」は既に分かっている事実に対して使うため合いません。' WHERE id = 'q-struct-c56';
UPDATE questions SET explanation = '後ろに主語と動詞を含む完全な節が続く場合は「Despite the fact that」を使います。「Despite」単独、「Despite of」、「of」を伴わない「In spite」は、いずれも節を直接後ろに置くことができません。' WHERE id = 'q-struct-c57';
UPDATE questions SET explanation = '「lest」は「〜しないように」という意味のややかたい接続詞で、後ろには仮定法現在(動詞の原形)である「collapse」が続きます。望ましくない事態を未然に防ぐ、という意味を表しています。' WHERE id = 'q-struct-c58';
UPDATE questions SET explanation = '「whereas(〜である一方)」は2つの事実を対比するときに使います。2つの地域の経済構造を比較しているこの文脈にぴったり合います。' WHERE id = 'q-struct-c59';
UPDATE questions SET explanation = '「as if / as though」が、見た瞬間よりも前に起きた出来事の結果としての状態を表す場合には、過去完了形「had been abandoned」を使います。' WHERE id = 'q-struct-c60';
UPDATE questions SET explanation = '「wish」を使って現在の事実に反する願望を表す場合、意味は現在のことでも動詞は過去形(仮定法過去)「had」を使います。' WHERE id = 'q-struct-c61';
UPDATE questions SET explanation = '「would rather + 主語 + 動詞」の形は、主語が話し手自身の動作ではない場合に使い、動詞には仮定法過去(were submitted)を使います。「is」「will be」「be」はこの構文には合いません。' WHERE id = 'q-struct-c62';
UPDATE questions SET explanation = '「It''s time + 主語 + 過去形」は「そろそろ〜すべき時だ、〜するのが遅すぎるくらいだ」という意味を表す仮定法的な決まり文句で、動詞には過去形「updated」を使います。' WHERE id = 'q-struct-c63';
UPDATE questions SET explanation = '「for」は「for over two decades(20年以上にわたって)」のように期間の長さを表すときに使います。一方「since」は起点となる時点を表すときに使います。' WHERE id = 'q-struct-c64';
UPDATE questions SET explanation = 'ここでは「〜に影響を与える」という意味の動詞"affect"が必要だが、通常は名詞として使われる"effect"になっている。"effect"を動詞として使うと「〜を引き起こす」という意味になり、この文の意図に合わない。' WHERE id = 'q-struct-e17';
UPDATE questions SET explanation = '"between"は2者の間を表すときに使う語。ここでは4人のきょうだいのように3者以上が対象になっているので、"among"を使う必要がある。' WHERE id = 'q-struct-e18';
UPDATE questions SET explanation = '「横になる」という意味の自動詞"lie"(lie–lay–lain)が必要。"lay"は他動詞で目的語を取る動詞なので、ここでは使えない。' WHERE id = 'q-struct-e19';
UPDATE questions SET explanation = '"since"で始まり、現在まで続く状態を表す節では現在完了形("have shared")を使う必要があり、単純過去形の"shared"は誤り。' WHERE id = 'q-struct-e20';
UPDATE questions SET explanation = '文頭の分詞構文"Arriving late to the meeting"は意味の上で人を修飾するはずだが、主節の主語が"the presentation"になっており、修飾先が宙に浮いた「懸垂分詞構文」になっている。主語は人にする必要がある(例:"he had already begun")。' WHERE id = 'q-struct-e21';
UPDATE questions SET explanation = '標準的なアメリカ英語では、"committee"のような集合名詞が1つのまとまりとして機能する場合は単数扱いの動詞を取るため、"The committee is meeting"が正しい。' WHERE id = 'q-struct-e22';
UPDATE questions SET explanation = '"avoid"の後には不定詞ではなく動名詞が続く。したがって"avoid to use"ではなく"avoid using"が正しい。' WHERE id = 'q-struct-e23';
UPDATE questions SET explanation = '"interested"の後に続く正しい前置詞は"on"ではなく"in"("interested in studying")。' WHERE id = 'q-struct-e24';
UPDATE questions SET explanation = '"harder"はすでに"hard"の比較級なので、さらに"more"を付けると二重比較級になってしまう。単に"harder than"とすればよい。' WHERE id = 'q-struct-e25';
UPDATE questions SET explanation = '"unique"は子音の音(「ユニーク」)で始まるため、前に置く冠詞は"an"ではなく"a"になる("a unique opportunity")。' WHERE id = 'q-struct-e26';
UPDATE questions SET explanation = '"however"だけでは2つの独立した節をコンマでつなぐことはできない。前にセミコロンを置くか("for repairs; however,")、2つの文に分ける必要がある。' WHERE id = 'q-struct-e27';
UPDATE questions SET explanation = '受動進行形には過去分詞"built"が必要で、原形の"build"は使えない("is being built")。' WHERE id = 'q-struct-e28';
UPDATE questions SET explanation = '"who"は人を指す関係代名詞。"laptop"は物なので、関係代名詞には"that"または"which"を使う必要がある("The laptop that crashed")。' WHERE id = 'q-struct-e29';
UPDATE questions SET explanation = '"hardly"はそれ自体が否定的な意味を持つ語なので、"couldn''t"と組み合わせると二重否定になってしまう。正しくは"could hardly remember"。' WHERE id = 'q-struct-e30';
UPDATE questions SET explanation = '"and"で結ばれた複合主語("The manager and the supervisor")は複数として扱われるため、動詞は"is responsible"ではなく"are responsible"が正しい。' WHERE id = 'q-struct-e31';
UPDATE questions SET explanation = '使役動詞"make"の後には"to"を伴わない原形の動詞(原形不定詞)が続く。したがって"made the players to run"ではなく"made the players run"が正しい。' WHERE id = 'q-struct-e32';
UPDATE questions SET explanation = '"it"の所有格は"its"(アポストロフィなし)。"it''s"は"it is"の短縮形であり、ここでは意味が合わない。' WHERE id = 'q-struct-e33';
UPDATE questions SET explanation = '"either...or"では、動詞は"or"に近い方の主語に一致させる。ここでは近い主語が複数形の"employees"なので、"are responsible"が正しい。' WHERE id = 'q-struct-e34';
UPDATE questions SET explanation = '"would rather"の直後には"to"を伴わない動詞の原形が続く。したがって"would rather to stay"ではなく"would rather stay"が正しい。' WHERE id = 'q-struct-e35';
UPDATE questions SET explanation = 'この代名詞は"invite"の目的語として機能している(you will invite whom)ため、フォーマルな文章では主格の"who"ではなく目的格の"whom"が必要になる。' WHERE id = 'q-struct-e36';
UPDATE questions SET explanation = '"the reason is because"は"reason"と"because"がどちらも原因を表すため、意味が重複してしまう。"the reason...is that"とするか、単に"the flight was delayed because of"とするのが正しい。' WHERE id = 'q-struct-e37';
UPDATE questions SET explanation = 'この時を表す節は"yesterday"という過去に完了した出来事を指しているため、動詞は単純過去形でなければならない("When I arrived")。' WHERE id = 'q-struct-e38';
UPDATE questions SET explanation = '関係代名詞"who"は複数名詞"employees"を指しているため、動詞も複数形の"meet"にする必要があり、"meets"は誤り。' WHERE id = 'q-struct-e39';
UPDATE questions SET explanation = '"as...as"の構文は同等比較を表すため両側に"as"が必要で、"than"は使えない。正しくは"not as efficient as the previous model"。' WHERE id = 'q-struct-e40';
UPDATE questions SET explanation = 'ここでの動詞"acted"は様態(どのように振る舞ったか)を表しているため、形容詞"professional"ではなく副詞"professionally"で修飾する必要がある。' WHERE id = 'q-struct-e41';
UPDATE questions SET explanation = '主語として機能する動名詞句("Collecting rare stamps")は単数として扱われるため、動詞は"have been"ではなく"has been"が正しい。' WHERE id = 'q-struct-e42';
UPDATE questions SET explanation = '過去の習慣を表す表現には"use to"ではなく"used to"が必要("She used to walk")。' WHERE id = 'q-struct-e43';
UPDATE questions SET explanation = '"there"の後に続く主語は複合主語"a wallet and several keys"であり複数扱いになるため、"There is"ではなく"There are"が正しい。' WHERE id = 'q-struct-e44';
UPDATE questions SET explanation = '正しい慣用表現は"similar with"ではなく"similar to"("similar to those reported")。' WHERE id = 'q-struct-e45';
UPDATE questions SET explanation = '"each and every one"は文法上単数として扱われるため、動詞は"were interviewed"ではなく"was interviewed"が正しい。' WHERE id = 'q-struct-e46';
UPDATE questions SET explanation = '主節に仮定を表す"would use"が使われており、これは第二条件文(仮定法過去)のif節と対応する形。したがって"increases"ではなく過去形の"If the government increased"にしないと時制が一致しない。' WHERE id = 'q-struct-e47';
UPDATE questions SET explanation = '「〜に加えて」という意味の"besides"が必要で、「〜の隣に」という意味の"beside"はここでは意味が合わない("Besides working as a nurse")。' WHERE id = 'q-struct-e48';
UPDATE questions SET explanation = '"rise"は物事がひとりでに増加することを表す自動詞(rise–rose–risen)。"raise"は他動詞で目的語を必要とするため、ここでは"Prices have risen"が正しい。' WHERE id = 'q-struct-e49';
UPDATE questions SET explanation = '"lend"は何かを一時的に「貸す」こと、"borrow"は何かを一時的に「借りる」ことを意味する。話し手は電卓を借りたい側なので、"Could you lend me"が正しい。' WHERE id = 'q-struct-e50';
UPDATE questions SET explanation = '"news"は常に単数扱いとなる不可算名詞なので、"were leaked"ではなく"the news...was leaked"が正しい。' WHERE id = 'q-struct-e51';
UPDATE questions SET explanation = '名詞の前では"so"ではなく"such a/an + 形容詞 + 名詞"の形を使う。正しくは"It was such a complicated problem"。' WHERE id = 'q-struct-e52';
UPDATE questions SET explanation = '"despite"は前置詞であり、"that"節を直接続けることはできない。"Despite the fact that"とするか、単に"Although the weather was poor"とする必要がある。' WHERE id = 'q-struct-e53';
UPDATE questions SET explanation = '最上級の形容詞には定冠詞"the"が必要("the best qualified candidate")。' WHERE id = 'q-struct-e54';
UPDATE questions SET explanation = '使役構文"have something done"には過去分詞が必要で、原形の"repair"は使えない。正しくは"had her car repaired"。' WHERE id = 'q-struct-e55';
UPDATE questions SET explanation = '"the majority of"の後に複数名詞("students")が続く場合は複数形の動詞を取るため、"has completed"ではなく"have completed"が正しい。' WHERE id = 'q-struct-e56';
UPDATE questions SET explanation = '本文は、遺伝子研究によって馬の家畜化に関する定説が、以前のカザフスタン草原説からヴォルガ・ドン地域説へと移り変わった経緯をたどっています。' WHERE id = 'q-read-horse-1';
UPDATE questions SET explanation = '本文には、以前の説が "rested largely on indirect evidence: wear patterns on horse teeth... and unusually large deposits of horse bones"(間接的な証拠、すなわち馬の歯のすり減り方や大量の馬の骨の堆積に大きく依拠していた)とあります。' WHERE id = 'q-read-horse-2';
UPDATE questions SET explanation = '"prevailing" は当時最も広く受け入れられていた見解、つまり「支配的な」見解を表します。' WHERE id = 'q-read-horse-3';
UPDATE questions SET explanation = '本文では、急速な広がりは "a calmer temperament and a stronger backbone"(穏やかな気性とより強靭な背骨)という特徴と結び付けられており、これらの特徴によって馬は制御しやすく、乗馬に適していました。' WHERE id = 'q-read-horse-4';
UPDATE questions SET explanation = 'この語句は、直前にある "a single population that lived in the lower Volga-Don region"(ヴォルガ・ドン下流域に生息していた単一の集団)という記述を指しています。' WHERE id = 'q-read-horse-5';
UPDATE questions SET explanation = '最終段落では輸送・戦争・交易が挙げられていますが、農業については本文中で触れられていません。' WHERE id = 'q-read-horse-6';
UPDATE questions SET explanation = '本文は、熱ストレスによってサンゴと藻類の共生関係が崩れ、白化現象が起こる仕組みを中心に述べています。' WHERE id = 'q-read-coral-1';
UPDATE questions SET explanation = '本文には藻類が "photosynthesize and supply the coral with nutrients"(光合成を行いサンゴに栄養を供給する)とあります。' WHERE id = 'q-read-coral-2';
UPDATE questions SET explanation = '"translucent" は白い骨格が透けて見える組織を表す語で、つまり「半透明の」という意味です。' WHERE id = 'q-read-coral-3';
UPDATE questions SET explanation = '白化は色を与えている藻類が失われた後に白い骨格が露出する現象なので、白化したサンゴ礁はより白っぽく、色が薄く見えるはずです。' WHERE id = 'q-read-coral-4';
UPDATE questions SET explanation = '第1段落でサンゴと藻類の共生関係が説明されており、第2段落の "this partnership" はそれを指しています。' WHERE id = 'q-read-coral-5';
UPDATE questions SET explanation = '本文には深刻な白化からの回復には "can take decades"(数十年かかることもある)とあり、1年以内に完全回復するという記述とは直接矛盾します。' WHERE id = 'q-read-coral-6';
UPDATE questions SET explanation = '本文は、印象派が侮蔑的な呼び名として始まり、やがて確立された芸術運動へと発展していった経緯をたどっています。' WHERE id = 'q-read-imp-1';
UPDATE questions SET explanation = '本文には、ある批評家が "mocking a Claude Monet painting... coined the term ''Impressionist'' as an insult"(クロード・モネの絵画をあざけって「印象派」という語を侮辱として作り出した)とあります。' WHERE id = 'q-read-imp-2';
UPDATE questions SET explanation = '"transient effects of natural light" は、すぐに変化する光の効果、つまり「一時的な」効果を指しています。' WHERE id = 'q-read-imp-3';
UPDATE questions SET explanation = '本文では、印象派の目に見える筆致と、"the smooth, blended surfaces the Salon prized"(サロンが高く評価していた滑らかで混ぜ合わされた画面)とが対比されています。' WHERE id = 'q-read-imp-4';
UPDATE questions SET explanation = 'この文は画商たちが "the artists'' work"(画家たちの作品)を売り込んでいたことを述べているので、"their" は画家たちを指します。' WHERE id = 'q-read-imp-5';
UPDATE questions SET explanation = '本文では駅・カフェ・川辺の集いが好んで描かれた題材として挙げられている一方、神話の場面は印象派が離れていった題材として述べられています。' WHERE id = 'q-read-imp-6';
UPDATE questions SET explanation = '本文は、膵臓に関する初期の研究からインスリンが発見され、それが急速に命を救う治療法へと発展していった経緯をたどっています。' WHERE id = 'q-read-insulin-1';
UPDATE questions SET explanation = '本文には、以前の試みが失敗したのは "largely because digestive enzymes in the pancreas broke down the substance before it could be extracted in usable form"(膵臓内の消化酵素が、その物質を使える形で抽出する前に分解してしまっていたため)とあります。' WHERE id = 'q-read-insulin-2';
UPDATE questions SET explanation = '"degenerate" は膵管を結紮した後に組織が劣化していく様子、つまり「分解する」ことを表しています。' WHERE id = 'q-read-insulin-3';
UPDATE questions SET explanation = '本文では、この方法によって酵素を産生する組織を分解させる一方で、"while preserving the cells now known to produce insulin"(現在インスリンを産生することが分かっている細胞は保存された)と説明されています。' WHERE id = 'q-read-insulin-4';
UPDATE questions SET explanation = 'コリップは抽出された物質を人間が安全に使えるように、抽出プロセスを改良しました。' WHERE id = 'q-read-insulin-5';
UPDATE questions SET explanation = '本文にはバンティング、ベスト、コリップ(およびマクラウド)の名前が挙げられていますが、アレクサンダー・フレミングについては触れられていません。' WHERE id = 'q-read-insulin-6';
UPDATE questions SET explanation = '本文は、ヒートアイランド現象の原因、その影響、そして都市が試みている対策について説明しています。' WHERE id = 'q-read-heat-1';
UPDATE questions SET explanation = '本文には、主な原因はアスファルトや濃い色の屋根材などが "absorb far more solar radiation... then slowly release that stored heat after sunset"(日中に太陽光をはるかに多く吸収し、日没後にその蓄えた熱をゆっくり放出する)ことだとあります。' WHERE id = 'q-read-heat-2';
UPDATE questions SET explanation = '"compound the effect" は他の要因がその効果をさらに強める、つまり「増強する」という意味です。' WHERE id = 'q-read-heat-3';
UPDATE questions SET explanation = '屋上緑化は、"reduce how much solar energy urban surfaces absorb and retain"(都市の表面が吸収・保持する太陽エネルギーの量を減らす)ことを目的とした対策の一つとして挙げられています。' WHERE id = 'q-read-heat-4';
UPDATE questions SET explanation = 'ここで言う熱とは、日中に都市の建築資材が吸収した太陽放射のことです。' WHERE id = 'q-read-heat-5';
UPDATE questions SET explanation = '本文では反射性のある屋根材、樹冠(緑地)の拡大、屋上緑化が対策として挙げられていますが、車両の禁止については触れられていません。' WHERE id = 'q-read-heat-6';
UPDATE questions SET explanation = '本文は、シルクロードが絹以外にもはるかに多くのものを運び、経済的・文化的に長く続く遺産を残したことを強調しています。' WHERE id = 'q-read-silkroad-1';
UPDATE questions SET explanation = '本文には、このネットワークは "following the rise of direct sea trade between Europe and Asia"(ヨーロッパとアジア間の直接海上貿易の台頭を受けて)衰退したとあります。' WHERE id = 'q-read-silkroad-2';
UPDATE questions SET explanation = '"disseminated" は、製紙技術が新しい地域に伝わった後に情報が記録され広まっていった様子を表しています。' WHERE id = 'q-read-silkroad-3';
UPDATE questions SET explanation = '本文には、これらの都市が繁栄したのは "largely because of their strategic locations rather than their own manufacturing output"(自らの生産力よりも主に戦略的な立地のおかげ)だとあります。' WHERE id = 'q-read-silkroad-4';
UPDATE questions SET explanation = 'この語句は、同じ文の前半で述べられているシルクロードのネットワークの衰退を指しています。' WHERE id = 'q-read-silkroad-5';
UPDATE questions SET explanation = '本文では香辛料、製紙技術、仏教の伝播について触れられていますが、火器については言及されていません。' WHERE id = 'q-read-silkroad-6';
UPDATE questions SET explanation = '本文はC4光合成の仕組みと、それが通常のC3光合成と比べてなぜ高温乾燥環境で有利になるのかを説明しています。' WHERE id = 'q-read-photosynthesis-1';
UPDATE questions SET explanation = '本文に "a wasteful side reaction... that reduces the energy available for growth" とあるように、RuBisCOが二酸化炭素の代わりに酸素と結合すると光呼吸が起こり、成長に使えるエネルギーが減少します。' WHERE id = 'q-read-photosynthesis-2';
UPDATE questions SET explanation = '"Suppressing the conditions that lead to photorespiration" は、光呼吸につながる条件が起こらないようにする、という意味です。' WHERE id = 'q-read-photosynthesis-3';
UPDATE questions SET explanation = '本文はC4植物が "hot, sunny climates" でも光合成を維持しながら水分を節約できると説明しており、そのため高温で日差しの強い気候において有利になります。' WHERE id = 'q-read-photosynthesis-4';
UPDATE questions SET explanation = '第2段落の冒頭でトウモロコシ、サトウキビ、ソルガムがここで説明されているC4植物の例として挙げられています。' WHERE id = 'q-read-photosynthesis-5';
UPDATE questions SET explanation = '本文はトウモロコシ、サトウキビ、ソルガムをC4植物として挙げていますが、小麦については触れていません。' WHERE id = 'q-read-photosynthesis-6';
UPDATE questions SET explanation = '本文は青銅器時代の崩壊の考えられる原因と、その影響が地域によってどう異なったかを論じています。' WHERE id = 'q-read-bronze-age-1';
UPDATE questions SET explanation = '本文には文字体系が "disappeared in several regions for centuries afterward" とあります。' WHERE id = 'q-read-bronze-age-2';
UPDATE questions SET explanation = '"Overwhelm these interconnected societies" は、複合的なストレスがこれらの社会の許容範囲を超えたことを意味します。' WHERE id = 'q-read-bronze-age-3';
UPDATE questions SET explanation = '本文は各社会が "grown economically interdependent through trade in tin and other resources needed to produce bronze" と説明しており、錫の交易が経済的な結びつきを生んでいたことがわかります。' WHERE id = 'q-read-bronze-age-4';
UPDATE questions SET explanation = 'このフレーズは第1段落で説明されている、崩壊の影響を受けた文明を指しています。' WHERE id = 'q-read-bronze-age-5';
UPDATE questions SET explanation = '本文は「海の民」による襲撃、長期の干ばつ、貿易網の崩壊に触れていますが、大規模な火山噴火については述べていません。' WHERE id = 'q-read-bronze-age-6';
UPDATE questions SET explanation = '本文は損失回避について説明し、それが合理的な経済モデルから外れた行動をどのように引き起こすかの例をいくつか挙げています。' WHERE id = 'q-read-loss-aversion-1';
UPDATE questions SET explanation = '本文に "feel the pain of a loss roughly twice as intensely as the pleasure of an equivalent gain" とあるように、人は損失の痛みを同額の利益の喜びの約2倍強く感じるとされています。' WHERE id = 'q-read-loss-aversion-2';
UPDATE questions SET explanation = '損失と利益を感じる強さの違いは非対称性(asymmetry)、つまり不均衡として説明されています。' WHERE id = 'q-read-loss-aversion-3';
UPDATE questions SET explanation = '本文には投資家が "often hold onto declining stocks far longer than a purely rational strategy would recommend" とあります。' WHERE id = 'q-read-loss-aversion-4';
UPDATE questions SET explanation = 'この文は、損失を避ける機会として値引きを見せる方法(より動機づけになる)を、利益として見せる場合と対比しています。' WHERE id = 'q-read-loss-aversion-5';
UPDATE questions SET explanation = '本文は投資家の行動、コイントスの賭け、小売業者の値引きの見せ方を例として挙げていますが、ブランドの好みについては触れていません。' WHERE id = 'q-read-loss-aversion-6';
UPDATE questions SET explanation = '本文はウェゲナーの当初の理論から海洋底拡大の発見を経て現代のプレートテクトニクス理論に至る流れをたどっています。' WHERE id = 'q-read-plate-tectonics-1';
UPDATE questions SET explanation = '本文には地質学者たちが理論を否定した理由として "largely because he could not identify a plausible mechanism" とあります。' WHERE id = 'q-read-plate-tectonics-2';
UPDATE questions SET explanation = '"Plausible mechanism" とは、信頼できる、説得力のある仕組みという意味です。' WHERE id = 'q-read-plate-tectonics-3';
UPDATE questions SET explanation = '本文には海洋底拡大が "provided the missing mechanism" とあり、ウェゲナーの理論に欠けていた仕組みを補ったことがわかります。' WHERE id = 'q-read-plate-tectonics-4';
UPDATE questions SET explanation = '"This framework" は、同じ段落の前半で説明されている現代のプレートテクトニクス理論を指しています。' WHERE id = 'q-read-plate-tectonics-5';
UPDATE questions SET explanation = '本文は一致する海岸線、海嶺(海洋底の中央海嶺)、地震・火山の分布について触れていますが、9番目の大陸の発見については述べていません。' WHERE id = 'q-read-plate-tectonics-6';
UPDATE questions SET explanation = '本文はグーテンベルクの印刷システムと、それがヨーロッパにおける知識の広がりに与えた幅広い影響を説明しています。' WHERE id = 'q-read-printing-press-1';
UPDATE questions SET explanation = '本文には "combined movable metal type, an oil-based ink suited to metal surfaces, and a modified wine press" とあります。' WHERE id = 'q-read-printing-press-2';
UPDATE questions SET explanation = '"Accelerate the spread of new scientific ideas" は、その広がりを加速させる、という意味です。' WHERE id = 'q-read-printing-press-3';
UPDATE questions SET explanation = '本文には手書きの写本が "limited to a small number of copies held by monasteries, universities, and wealthy patrons" とあります。' WHERE id = 'q-read-printing-press-4';
UPDATE questions SET explanation = '本文は、印刷術を持たなかった以前の改革者たちと比べて、ルターが印刷術を使っていかに速く自分の著作を広められたかを対比しています。' WHERE id = 'q-read-printing-press-5';
UPDATE questions SET explanation = '本文は書籍のコスト低下、科学的思想の広がりの加速、識字率の上昇に触れていますが、修道院の廃止については述べていません。' WHERE id = 'q-read-printing-press-6';
UPDATE questions SET explanation = '本文はタコの分散型神経系と、それが素早い擬態をどう支えているかを説明しています。' WHERE id = 'q-read-octopus-1';
UPDATE questions SET explanation = '本文には "roughly two-thirds of an octopus''s several hundred million neurons are distributed throughout its eight arms" とあります。' WHERE id = 'q-read-octopus-2';
UPDATE questions SET explanation = '"Distributed throughout its eight arms" は、一箇所に集中せず8本の腕全体に広がっている、という意味です。' WHERE id = 'q-read-octopus-3';
UPDATE questions SET explanation = '本文はタコが "are believed to be colorblind" にもかかわらず周囲の色に合わせられる点が謎だと述べています。' WHERE id = 'q-read-octopus-4';
UPDATE questions SET explanation = '"This ability" は、第2段落の冒頭で紹介された、瞬時に近い擬態能力を指しています。' WHERE id = 'q-read-octopus-5';
UPDATE questions SET explanation = '本文はタコには色感受性の錐体細胞が欠けていると述べており、色素胞・乳頭・皮膚の光感受性タンパク質はいずれも擬態に関わるものとして挙げられています。' WHERE id = 'q-read-octopus-6';
UPDATE questions SET explanation = '本文はダストボウルの自然的・人為的な原因と、それが農家や政策に与えた影響を説明しています。' WHERE id = 'q-read-dust-bowl-1';
UPDATE questions SET explanation = '本文には農家が "had plowed under vast areas of native prairie grasses to plant wheat" とあります。' WHERE id = 'q-read-dust-bowl-2';
UPDATE questions SET explanation = '"Anchored the soil" は、土壌をしっかりと固定していた、という意味です。' WHERE id = 'q-read-dust-bowl-3';
UPDATE questions SET explanation = '草原の草が土壌を固定し浸食を防いでいたため、それが耕されずに残っていればダストボウルの被害はより小さかったと考えられます。' WHERE id = 'q-read-dust-bowl-4';
UPDATE questions SET explanation = 'この文は、直前で述べられた深く根を張った草原の草が "without" だった場合に表土がどうなるかを説明しています。' WHERE id = 'q-read-dust-bowl-5';
UPDATE questions SET explanation = '本文は干ばつ、耕作の慣行、政府の土壌保全事業に触れていますが、大規模な灌漑用水路の建設については述べていません。' WHERE id = 'q-read-dust-bowl-6';
UPDATE questions SET explanation = '本文はパトロン制度がルネサンス美術の制作内容や、芸術家同士の競争のあり方をどう形作ったかを説明しています。' WHERE id = 'q-read-renaissance-patronage-1';
UPDATE questions SET explanation = '本文には依頼内容が "exact dimensions, materials such as expensive pigments... and even the number of figures to be included" を指定しうるとあります。' WHERE id = 'q-read-renaissance-patronage-2';
UPDATE questions SET explanation = 'パトロンの好みが創作の選択を "constrained" したというのは、それらを制限したという意味です。' WHERE id = 'q-read-renaissance-patronage-3';
UPDATE questions SET explanation = '本文は芸術家が "had strong incentives to satisfy a patron''s specific tastes and demands" と説明しています。' WHERE id = 'q-read-renaissance-patronage-4';
UPDATE questions SET explanation = '"This arrangement" は、第1段落で紹介されたパトロン制度を指しています。' WHERE id = 'q-read-renaissance-patronage-5';
UPDATE questions SET explanation = '本文は富や政治的影響力の誇示、競争による技術革新の促進、パトロンの好みを満たすことに触れていますが、熟練した芸術家の必要性をなくすことには触れておらず、むしろ本文の内容と矛盾します。' WHERE id = 'q-read-renaissance-patronage-6';
UPDATE questions SET explanation = '本文は渡り鳥が長距離を移動する際に用いる、地磁気感知・天体の位置・記憶地図など複数の重なり合うナビゲーションの仕組みを説明しています。' WHERE id = 'q-read-bird-navigation-1';
UPDATE questions SET explanation = '本文は磁気受容を "the ability to detect Earth''s magnetic field" と定義しています。' WHERE id = 'q-read-bird-navigation-2';
UPDATE questions SET explanation = '"Innate rather than learned" な能力とは、生まれつき備わっている能力のことです。' WHERE id = 'q-read-bird-navigation-3';
UPDATE questions SET explanation = '本文には若い鳥が "often complete the journey successfully even without prior experience or adult guidance" とあり、生まれつきの能力があることが示唆されています。' WHERE id = 'q-read-bird-navigation-4';
UPDATE questions SET explanation = '"This sense" は、その段落の前半で説明されている、地磁気を感知する磁気受容感覚を指しています。' WHERE id = 'q-read-bird-navigation-5';
UPDATE questions SET explanation = '本文は地磁気、太陽や星の位置、目印や匂いに触れていますが、他の鳥からの電波信号については述べていません。' WHERE id = 'q-read-bird-navigation-6';
UPDATE questions SET explanation = '本文は組み立てライン(アセンブリーライン)が製造効率をどう変え、産業全体に長期的な影響を与えたかを説明しています。' WHERE id = 'q-read-assembly-line-1';
UPDATE questions SET explanation = '本文には工場が "reduced the time required to build a single car to roughly ninety minutes" とあります。' WHERE id = 'q-read-assembly-line-2';
UPDATE questions SET explanation = '"Monotony of repetitive tasks" は、単純作業の反復性を表しています。' WHERE id = 'q-read-assembly-line-3';
UPDATE questions SET explanation = '本文には賃金上昇の理由として "in part to reduce the high turnover caused by the monotony of repetitive tasks" とあります。' WHERE id = 'q-read-assembly-line-4';
UPDATE questions SET explanation = 'この文は、組み立てラインによる効率性の向上と、それが同時に受けた批判とを対比しています。' WHERE id = 'q-read-assembly-line-5';
UPDATE questions SET explanation = '本文は建造時間の短縮、価格低下、単純労働化への批判に触れていますが、工場労働の完全な消滅については述べていません。' WHERE id = 'q-read-assembly-line-6';
UPDATE questions SET explanation = '本文は、永久凍土の融解が二酸化炭素とメタンを放出し、温暖化を加速させるフィードバックループを生み出す仕組みを説明しています。' WHERE id = 'q-read-permafrost-1';
UPDATE questions SET explanation = '本文には、低温によって分解を担う微生物の働きが妨げられていたため、有機物の分解が止まっていたとあります。' WHERE id = 'q-read-permafrost-2';
UPDATE questions SET explanation = '「Long-dormant organic material」は、長期間活動を停止した(=分解が進んでいない)物質を表しています。' WHERE id = 'q-read-permafrost-3';
UPDATE questions SET explanation = '本文には、新たに放出されるこの炭素は「以前は閉じ込められており、過去の気候予測には織り込まれていなかった("was previously locked away and not accounted for in earlier climate projections")」とあります。' WHERE id = 'q-read-permafrost-4';
UPDATE questions SET explanation = 'この文は、インフラの下にある地面(永久凍土)が融解し、不均一に沈下していく様子を説明しています。' WHERE id = 'q-read-permafrost-5';
UPDATE questions SET explanation = '本文では融解の影響を受けるものとして建物・道路・パイプラインが挙げられていますが、海流については言及がありません。' WHERE id = 'q-read-permafrost-6';
UPDATE questions SET explanation = '本文は、ハンムラビ法典の内容と構成、そして1901年の再発見の経緯を説明しています。' WHERE id = 'q-read-hammurabi-1';
UPDATE questions SET explanation = '本文に「法典は282の個別の法から成る("consists of 282 individual laws")」とあります。' WHERE id = 'q-read-hammurabi-2';
UPDATE questions SET explanation = '「Proportional retaliation」(比例的な報復)とは、「目には目を("an eye for an eye")」のように罪の重さに見合った罰を意味します。' WHERE id = 'q-read-hammurabi-3';
UPDATE questions SET explanation = '本文には、実際に科される罰は「加害者と被害者双方の社会的地位に大きく左右されることが多かった("often depended heavily on the social status of both the offender and the victim")」とあります。' WHERE id = 'q-read-hammurabi-4';
UPDATE questions SET explanation = 'この文は、ハンムラビ法典が刻まれた石碑(stele)が再発見されたことについて述べています。' WHERE id = 'q-read-hammurabi-5';
UPDATE questions SET explanation = '本文では財産をめぐる紛争・労働者の賃金・欠陥工事の責任などが挙げられていますが、宗教儀礼に関する規定については言及がありません。' WHERE id = 'q-read-hammurabi-6';
UPDATE questions SET explanation = '本文は、菌類と光合成を行うパートナーがどのように結びついて地衣類という複合生物を形成するかを説明しています。' WHERE id = 'q-read-lichen-1';
UPDATE questions SET explanation = '本文には、光合成を行うパートナーが「菌類が自ら作り出せない炭水化物を供給する("supplies the fungus with the carbohydrates it cannot manufacture on its own")」とあります。' WHERE id = 'q-read-lichen-2';
UPDATE questions SET explanation = '菌類は光合成パートナーを強い日光や乾燥(desiccation、つまり水分が失われて乾ききってしまうこと)から守っています。' WHERE id = 'q-read-lichen-3';
UPDATE questions SET explanation = '本文には、菌類は「クロロフィルを持たない("lack chlorophyll")」ため、炭水化物の供給を光合成パートナーに頼っているとあります。' WHERE id = 'q-read-lichen-4';
UPDATE questions SET explanation = 'この段落は、地衣類が大気汚染物質に敏感であることが、大気質の指標として利用される理由になっていると説明しています。' WHERE id = 'q-read-lichen-5';
UPDATE questions SET explanation = '本文では熱帯雨林・北極の裸岩・樹皮が地衣類の生育環境として挙げられていますが、海底については言及がありません。' WHERE id = 'q-read-lichen-6';
UPDATE questions SET explanation = '本文は、ジェンナーの実験、「種痘(vaccination)」という用語の誕生、そしてその後の世界的な普及という流れを追っています。' WHERE id = 'q-read-vaccination-1';
UPDATE questions SET explanation = '本文には、民間伝承では牛痘にかかったことのある乳搾りの女性たちは「天然痘にほとんどかからなかった("rarely contracted smallpox at all")」と信じられていたとあります。' WHERE id = 'q-read-vaccination-2';
UPDATE questions SET explanation = '人痘接種法(variolation)は、軽い症状を誘発する(induce、つまり引き起こす)ことを狙ったものでした。' WHERE id = 'q-read-vaccination-3';
UPDATE questions SET explanation = '本文には、人痘接種法は天然痘の膿を用いており、「時に致命的な感染を引き起こすことがあった("sometimes caused fatal infections")」とあります。' WHERE id = 'q-read-vaccination-4';
UPDATE questions SET explanation = '「This procedure」は、ジェンナーが少年に対して行ったばかりの、牛痘を用いた接種法を指します。' WHERE id = 'q-read-vaccination-5';
UPDATE questions SET explanation = '本文では人痘接種法・牛痘・ジェンナーについて述べられていますが、ウイルス性の病気には効かない抗生物質については触れられていません。' WHERE id = 'q-read-vaccination-6';
UPDATE questions SET explanation = '本文は、産業革命期の急激な都市化が劣悪な生活環境を生み、やがて公衆衛生改革へとつながっていった経緯を追っています。' WHERE id = 'q-read-urbanization-1';
UPDATE questions SET explanation = '本文には、マンチェスターは「1770年には人口約2万5千人の小さな市場町だったが、数十年のうちに数十万人規模の都市へと成長した("grew from a modest market town of about twenty-five thousand people in 1770 to a city of several hundred thousand")」とあります。' WHERE id = 'q-read-urbanization-2';
UPDATE questions SET explanation = '成長が行政のサービス提供能力を「outpaced(上回った)」というのは、行政の対応が追いつく速さを成長が超えてしまったという意味です。' WHERE id = 'q-read-urbanization-3';
UPDATE questions SET explanation = '本文には、多くの世帯が一つの水源やトイレを共有しており、それが疾病の蔓延にとって理想的な状況を生み出したとあります。' WHERE id = 'q-read-urbanization-4';
UPDATE questions SET explanation = '直前の段落では、コレラの流行が工業都市に何度も広がっていった様子が説明されています。' WHERE id = 'q-read-urbanization-5';
UPDATE questions SET explanation = '本文では過密な集合住宅・共有の水源やトイレ・コレラの流行が挙げられていますが、工場労働者の減少については言及がありません。' WHERE id = 'q-read-urbanization-6';
UPDATE questions SET explanation = '本文は、エコーロケーション(反響定位)の仕組みと、それを可能にする身体的な適応について説明しています。' WHERE id = 'q-read-echolocation-1';
UPDATE questions SET explanation = '本文には、コウモリは「距離と方向...大きさ、形、質感、さらには動いているかどうかまで("distance and direction... size, shape, texture, and even whether it is moving")」判別できるとあります。' WHERE id = 'q-read-echolocation-2';
UPDATE questions SET explanation = '「Faint returning echoes」とは、コウモリ自身の鳴き声に比べて弱く、感知しにくい反響音を指します。' WHERE id = 'q-read-echolocation-3';
UPDATE questions SET explanation = '本文は、この仕組みがコウモリを「自分自身の鳴き声によって耳が聞こえなくなること("from being deafened by its own call")」から守っていると説明しています。' WHERE id = 'q-read-echolocation-4';
UPDATE questions SET explanation = '技術者たちは、ソナーやレーダーを開発する際にエコーロケーションの基本原理を応用しました。' WHERE id = 'q-read-echolocation-5';
UPDATE questions SET explanation = '本文では喉頭の筋肉・耳の形・中耳の仕組みについて述べられていますが、赤外線視覚については触れられていません。' WHERE id = 'q-read-echolocation-6';
UPDATE questions SET explanation = '本文は、失敗に終わったフランスによる試みと、それに続くアメリカによるパナマ運河の完成とを対比しています。' WHERE id = 'q-read-panama-1';
UPDATE questions SET explanation = '本文には、このプロジェクトは「財政の失敗、不安定な山岳地形、そして...病気が重なって("defeated by a combination of financial mismanagement, unstable mountainous terrain, and... disease")」失敗したとあります。' WHERE id = 'q-read-panama-2';
UPDATE questions SET explanation = '病気は、フランスのプロジェクトを失敗させた原因の中でも最も「devastating(壊滅的)」、つまり最も破壊的なものとして描かれています。' WHERE id = 'q-read-panama-3';
UPDATE questions SET explanation = '本文には、フランスの試みの当時は蚊と病気の関係が「まだ理解されていなかった("was not yet understood")」とあり、これが流行を制御できなかった理由を説明しています。' WHERE id = 'q-read-panama-4';
UPDATE questions SET explanation = 'この文は、ガトゥン湖を利用した閘門(こうもん)方式の説明の直後に続くものです。' WHERE id = 'q-read-panama-5';
UPDATE questions SET explanation = '本文では閘門方式・ガトゥン湖・ゴーガス医師による蚊の駆除活動について述べられていますが、ダイナマイトの発明については言及がありません。' WHERE id = 'q-read-panama-6';
UPDATE questions SET explanation = '本文は、認知的不協和理論と、人々が矛盾する信念をどのように解消するかについて説明しています。' WHERE id = 'q-read-dissonance-1';
UPDATE questions SET explanation = '本文には、メンバーたちは「失敗した予言を、自分たちの信仰が世界を救った証拠だと再解釈した("reinterpreted the failed prophecy as evidence that their faith had saved the world")」とあります。' WHERE id = 'q-read-dissonance-2';
UPDATE questions SET explanation = 'フェスティンガーは、不協和は「積極的に人を動かすもの("actively motivating")」であり、人々を矛盾の解消へと駆り立てると論じました。' WHERE id = 'q-read-dissonance-3';
UPDATE questions SET explanation = '本文には、この理論は、過去の投資が誤りだったと認めることを避けるために、失敗しつつあるプロジェクトへの投資を続けてしまう理由を説明できるとあります。' WHERE id = 'q-read-dissonance-4';
UPDATE questions SET explanation = 'この段落は、認知的不協和理論が幅広く応用されてきたと述べたうえで、「It」はその理論を指し続けています。' WHERE id = 'q-read-dissonance-5';
UPDATE questions SET explanation = '本文では、正当化する新たな信念を加えること・信念に合わせて行動を変えること・矛盾の重要性を軽視することが挙げられていますが、心理療法を受けることへの言及はありません。' WHERE id = 'q-read-dissonance-6';
UPDATE questions SET explanation = '本文は、砂漠の植物や動物が水不足と極端な気温差にどのように適応してきたかを概観しています。' WHERE id = 'q-read-desert-1';
UPDATE questions SET explanation = '本文には、多くの砂漠の植物は水を失いやすい広い葉の代わりに「小さく針のような葉やとげを持つ("small, needle-like leaves or spines")」とあります。' WHERE id = 'q-read-desert-2';
UPDATE questions SET explanation = '広い葉は「transpiration(蒸散)」、つまり植物の表面から水蒸気が失われる現象によって急速に水分を失います。' WHERE id = 'q-read-desert-3';
UPDATE questions SET explanation = '本文は、気孔が夜間に開くのは「気温が低く、失われる水分が少ないから("when temperatures are lower and less water is lost")」だと説明しています。' WHERE id = 'q-read-desert-4';
UPDATE questions SET explanation = 'この文は、カンガルーネズミが乾燥した種子を消化する過程で体内に作られる水分だけで、ほぼ生きていけることを説明しています。' WHERE id = 'q-read-desert-5';
UPDATE questions SET explanation = '本文では夜行性の行動・多肉植物による貯水・効率的な腎臓が挙げられていますが、移動(migration)については言及がありません。' WHERE id = 'q-read-desert-6';
